import treeofcolor
from itertools import repeat

# we use itertools to allow us to simplify our lights!
# we don't want to create a list of 500 green lights,
# so instead, we pass an iterator generated by `repeat`:
# https://docs.python.org/3/library/itertools.html#itertools.repeat

# if you want to, you can also `print` debug information
# and it will go to the `Terminal`!

if __name__ == '__main__':
    color = treeofcolor.Color(0, 255, 0) # this variable sets the color using RGB

    def frame_producer():
        return treeofcolor.Frame(repeat(color)) # were using whatever read above
        
    solid_color = treeofcolor.App(frame_producer)
    solid_color.run()
