import treeofcolor
from itertools import repeat

if __name__ == '__main__':
    green = treeofcolor.Color(0, 255, 0)
    def frame_producer():
        # we use itertools to allow us to simplify our lights!
        # we don't want to create a list of 500 green lights,
        # so instead, we pass an iterator generated by `repeat`:
        # https://docs.python.org/3/library/itertools.html#itertools.repeat
        return treeofcolor.Frame(repeat(green))

    # if you want to, you can also `print` debug information
    # and it will go to the `Terminal`!

    solid_color = treeofcolor.App(frame_producer)
    solid_color.run()
